server:
  port: 8089

spring:
  application:
    name: vinilos9

  datasource:
    url: jdbc:mysql://localhost:3306/db_resena
    username: root
    password:

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
