server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: cliente-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/clientes/**

        - id: producto-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/productos/**

        - id: pedido-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/pedidos/**

        - id: pago-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/pagos/**

        - id: envio-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/envios/**

        - id: inventario-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/inventarios/**

        - id: notificacion-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/notificaciones/**

logging:
  level:
    org.springframework.cloud.gateway: INFO